apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlassian-sync
  namespace: cogni-sync
  labels:
    app: atlassian-sync
    service: atlassian-sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atlassian-sync
  template:
    metadata:
      labels:
        app: atlassian-sync
        service: atlassian-sync
    spec:
      containers:
      - name: atlassian-sync
        image: cognisync/atlassian-sync:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: cogni-sync-config
              key: NODE_ENV
        - name: PORT
          value: "3002"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cogni-sync-secrets
              key: atlassian-database-url
        - name: VALID_API_KEYS
          valueFrom:
            secretKeyRef:
              name: cogni-sync-secrets
              key: atlassian-sync-api-keys
        - name: KG_SERVICE_URL
          value: "http://knowledge-graph:3001/api/v1"
        - name: KG_API_KEY
          valueFrom:
            secretKeyRef:
              name: cogni-sync-secrets
              key: kg-api-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cogni-sync-secrets
              key: jwt-secret
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: cogni-sync-config
              key: CORS_ORIGIN
        - name: AZURE_SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: cogni-sync-secrets
              key: azure-service-bus-connection-string
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: atlassian-sync
  namespace: cogni-sync
  labels:
    app: atlassian-sync
spec:
  selector:
    app: atlassian-sync
  ports:
  - port: 3002
    targetPort: 3002
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlassian-sync-ingress
  namespace: cogni-sync
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - atlassian-sync.your-domain.com
    secretName: atlassian-sync-tls
  rules:
  - host: atlassian-sync.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: atlassian-sync
            port:
              number: 3002