apiVersion: v1
kind: Secret
metadata:
  name: cogni-sync-secrets
  namespace: cogni-sync
type: Opaque
stringData:
  # Database credentials
  postgres-password: "your-postgres-password"
  neo4j-password: "your-neo4j-password"
  
  # JWT and API keys
  jwt-secret: "your-jwt-secret-key"
  api-key-salt: "your-api-key-salt"
  kg-api-key: "your-kg-api-key"
  atlassian-sync-api-keys: "AS-SYNC-PROD-KEY-1,AS-SYNC-PROD-KEY-2"
  
  # External service keys
  openai-api-key: "your-openai-api-key"
  openai-org-id: "your-openai-org-id"
  pinecone-api-key: "your-pinecone-api-key"
  
  # Service Bus
  azure-service-bus-connection-string: "your-service-bus-connection-string"
  
  # Database URLs
  atlassian-database-url: "postgresql://cogni_sync:password@postgres:5432/atlassian_sync"
  kg-database-url: "postgresql://cogni_sync:password@postgres:5432/knowledge_graph"
  rag-database-url: "postgresql://cogni_sync:password@postgres:5432/llm_rag"
  
  # Neo4j
  neo4j-uri: "neo4j://neo4j:7687"
  neo4j-username: "neo4j"